//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbellAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarbellAnalysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05/12/2008 16:56:00,&quot;35,35&quot;
        ///12/12/2008 16:56:00,&quot;39,11&quot;
        ///19/12/2008 16:56:00,&quot;39,13&quot;
        ///26/12/2008 16:56:00,&quot;36,9&quot;
        ///02/01/2009 16:56:00,&quot;40,32&quot;
        ///09/01/2009 16:56:00,42
        ///16/01/2009 16:56:00,&quot;39,49&quot;
        ///23/01/2009 16:56:00,&quot;38,08&quot;
        ///30/01/2009 16:56:00,&quot;39,6&quot;
        ///06/02/2009 16:56:00,&quot;43,2&quot;
        ///13/02/2009 16:56:00,&quot;41,85&quot;
        ///20/02/2009 16:56:00,&quot;39,2&quot;
        ///27/02/2009 16:56:00,&quot;38,75&quot;
        ///06/03/2009 16:56:00,&quot;37,5&quot;
        ///13/03/2009 16:56:00,&quot;39,2&quot;
        ///20/03/2009 16:56:00,&quot;40,2&quot;
        ///27/03/2009 16:56:00,&quot;41,74&quot;
        ///03/04/2009 16:56:00,&quot;44,55&quot;
        ///09 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BOVA11 {
            get {
                return ResourceManager.GetString("BOVA11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/01/2008,&quot;6,68&quot;
        ///01/02/2008,&quot;6,04&quot;
        ///01/03/2008,&quot;5,92&quot;
        ///01/04/2008,&quot;6,8&quot;
        ///01/05/2008,&quot;9,9&quot;
        ///01/06/2008,&quot;9,25&quot;
        ///01/07/2008,&quot;6,55&quot;
        ///01/08/2008,&quot;3,41&quot;
        ///01/09/2008,&quot;3,16&quot;
        ///01/10/2008,&quot;5,54&quot;
        ///01/11/2008,&quot;4,41&quot;
        ///01/12/2008,&quot;3,41&quot;
        ///01/01/2009,&quot;5,91&quot;
        ///01/02/2009,&quot;6,8&quot;
        ///01/03/2009,&quot;2,42&quot;
        ///01/04/2009,&quot;5,92&quot;
        ///01/05/2009,&quot;5,79&quot;
        ///01/06/2009,&quot;4,41&quot;
        ///01/07/2009,&quot;2,92&quot;
        ///01/08/2009,&quot;1,81&quot;
        ///01/09/2009,&quot;2,92&quot;
        ///01/10/2009,&quot;3,41&quot;
        ///01/11/2009,&quot;5,03&quot;
        ///01/12/2009,&quot;4,53&quot;
        ///01/01/2010,&quot;9,38&quot;
        ///01/02/2010,&quot;9,77&quot;
        ///01/03/2010,&quot;6,42&quot;
        ///01 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IPCA {
            get {
                return ResourceManager.GetString("IPCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/01/2008,&quot;0,93&quot;
        ///01/02/2008,&quot;0,80&quot;
        ///01/03/2008,&quot;0,84&quot;
        ///01/04/2008,&quot;0,90&quot;
        ///01/05/2008,&quot;0,88&quot;
        ///01/06/2008,&quot;0,96&quot;
        ///01/07/2008,&quot;1,07&quot;
        ///01/08/2008,&quot;1,02&quot;
        ///01/09/2008,&quot;1,10&quot;
        ///01/10/2008,&quot;1,18&quot;
        ///01/11/2008,&quot;1,02&quot;
        ///01/12/2008,&quot;1,12&quot;
        ///01/01/2009,&quot;1,05&quot;
        ///01/02/2009,&quot;0,86&quot;
        ///01/03/2009,&quot;0,97&quot;
        ///01/04/2009,&quot;0,84&quot;
        ///01/05/2009,&quot;0,77&quot;
        ///01/06/2009,&quot;0,76&quot;
        ///01/07/2009,&quot;0,79&quot;
        ///01/08/2009,&quot;0,69&quot;
        ///01/09/2009,&quot;0,69&quot;
        ///01/10/2009,&quot;0,69&quot;
        ///01/11/2009,&quot;0,66&quot;
        ///01/12/2009,&quot;0,73&quot;
        ///01/01/2010,&quot;0,66&quot;
        ///01/02/2010,&quot;0,59&quot;
        ///01/03/2010,&quot;0,76&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SELIC {
            get {
                return ResourceManager.GetString("SELIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05/12/2008 23:58:00,&quot;2,566&quot;
        ///12/12/2008 23:58:00,&quot;2,3495&quot;
        ///19/12/2008 23:58:00,&quot;2,3705&quot;
        ///26/12/2008 23:58:00,&quot;2,3261&quot;
        ///02/01/2009 23:58:00,&quot;2,313&quot;
        ///09/01/2009 23:58:00,&quot;2,2431&quot;
        ///16/01/2009 23:58:00,&quot;2,29&quot;
        ///23/01/2009 23:58:00,&quot;2,3002&quot;
        ///30/01/2009 23:58:00,&quot;2,263&quot;
        ///06/02/2009 23:58:00,&quot;2,2593&quot;
        ///13/02/2009 23:58:00,&quot;2,256&quot;
        ///20/02/2009 23:58:00,&quot;2,3905&quot;
        ///27/02/2009 23:58:00,&quot;2,369&quot;
        ///06/03/2009 23:58:00,&quot;2,3724&quot;
        ///13/03/2009 23:58:00,&quot;2,3065&quot;
        ///20/03/2009 23:58:00,&quot;2,264&quot;
        ///27/03/2009 23:58:00,&quot;2,2754&quot;
        ///03/04/2009 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
    }
}
